sudo: false

language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4.5
    - otp_release: 20.1
      elixir: 1.6.1

script:
  - if [[ $(elixir --version) = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test --trace
