sudo: false

language: elixir

otp_release: '21.1'
elixir: '1.8'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test

    - otp_release: '18.3'
      elixir: '1.4'

    - stage: check formatted
      script: mix format --check-formatted
